version: '3.8'
services:
  product-service:
    image: product-service
    build:
      context: ../product-service
      dockerfile: Dockerfile
    ports:
      - "9090-8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
  order-service:
    image: order-service
    build:
      context: ../order-service
      dockerfile: Dockerfile
    ports:
      - "7070-8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - "6379:6379"