version: '3.8'
services:
  product-service:
    image: product-service
    build:
      context: ../product-service
      dockerfile: Dockerfile
    ports:
      - "8080-8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
  order-service:
    image: order-service
    build:
      context: ../order-service
      dockerfile: Dockerfile
    ports:
      - "8081-8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect