global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8081' ]
  - job_name: "order-service"
    metrics_path:  '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8082']
